apiVersion: k3d.io/v1alpha4
kind: Simple
servers: 2
agents: 2
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"

ports:
  - port: 80:80 # http port host:container
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:443:443 # https port host:container
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
  # k3s:
  # extraServerArgs: []
  # extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
